use chrono;

pub fn generate_markdown(chat_history: &str) -> String {
    let date = chrono::Local::now().format("%B %d, %Y").to_string();
    
    let formatted_history = chat_history
        .replace("\nUser: ", "\n\n### 💭 You\n")
        .replace("\nAI: ", "\n\n### 💛 Lumi\n");
    
    format!(
        "# ✨ Journal Entry - {}\n\n{}\n\n---\n\n*Generated by Lumi, your AI journaling companion*",
        date,
        formatted_history.trim_start()
    )
} 