use chrono;

/// Generate a simple markdown journal from chat history (used as fallback)
pub fn generate_markdown(chat_history: &str) -> String {
    let date = chrono::Local::now().format("%B %d, %Y").to_string();
    
    // Extract user messages from the conversation
    let user_messages: Vec<&str> = chat_history
        .split("\n")
        .filter(|line| line.starts_with("User: "))
        .map(|line| line.trim_start_matches("User: "))
        .collect();
    
    let mut journal = format!("# ✨ Journal Entry - {}\n\n", date);
    
    if user_messages.is_empty() {
        journal.push_str("*No conversation recorded yet.*\n\n");
    } else {
        // Personal reflection section
        journal.push_str("## My Reflections\n\n");
        journal.push_str("Today I took some time to write down my thoughts and reflect on what's been on my mind. ");
        journal.push_str("It's been helpful to express myself and process my thoughts through journaling.\n\n");
        
        // Key thoughts section based on what the user said
        journal.push_str("## Key Thoughts\n\n");
        
        // Use the user's own words in the form of reflections
        for (i, msg) in user_messages.iter().take(3).enumerate() {
            if i == 0 {
                journal.push_str("Today I was thinking about ");
            } else if i == user_messages.len() - 1 && i > 0 {
                journal.push_str("I also considered ");
            } else {
                journal.push_str("Then I reflected on ");
            }
            
            // Clean up and format the user message as a reflection
            let reflection = msg
                .trim()
                .trim_end_matches(".")
                .to_lowercase()
                .replace("i ", "I ")
                .replace("i'm", "I'm")
                .replace("i'd", "I'd")
                .replace("i've", "I've");
            
            journal.push_str(&format!("{}.\n\n", reflection));
        }
        
        // Personal insights section
        journal.push_str("## Insights Gained\n\n");
        journal.push_str("Through this reflection, I've come to realize a few things about myself:\n\n");
        journal.push_str("- I need to take time regularly to process my thoughts\n");
        journal.push_str("- Writing down my feelings helps me understand them better\n");
        journal.push_str("- There's value in reviewing my thoughts later to see patterns\n\n");
    }
    
    // Looking forward section
    journal.push_str("## Looking Forward\n\n");
    journal.push_str("Tomorrow, I'd like to continue this practice of reflection and see what new insights emerge. ");
    journal.push_str("I'm grateful for this space to express myself.\n\n");
    
    journal.push_str("---\n\n");
    journal.push_str("*Generated by Olly, your AI journaling companion*");
    
    journal
} 